#!/usr/bin/env python3
"""s12_ruler.py — S12: RULER long-context accuracy vs quantization.

WHY THIS AND NOT S10/S11
  The question is whether quantization damage grows with context depth. S10 (KL divergence at
  depth) is infeasible here — llama-perplexity holds a chunk's logits resident and this host caps
  at n_ctx 8,192 (PN-31). S11 (greedy divergence at depth) was built, run, and REJECTED on its own
  data: free-running greedy trajectories fork within a few tokens, after which every pairwise
  distance sits at 0.61-0.79 regardless of ladder position — adjacent arms measured further apart
  than the extremes. Neither is the method the field uses.

WHAT THE FIELD USES
  RULER (arXiv 2404.06654, NVIDIA) — synthetic long-context tasks generated at a controlled
  sequence length, scored by string match, compared as ACCURACY RECOVERY against an unquantized
  (here: least-quantized) baseline per length. Two published studies do exactly our experiment
  with it:
    - Red Hat, "How well do quantized models handle long-context tasks?" — RULER on Llama-3.1
      8B/70B at 4K-128K across FP W8A8 / INT W8A8 / INT W4A16. Result: >99.5 % recovery at most
      lengths, but INT W4A16 at 128K falls to 85-88 %.
    - arXiv 2505.20276, "Does quantization affect models' performance on long-context tasks?" —
      9.7K examples, 5 models x 5 schemes. 8-bit ~0.8 % drop; 4-bit up to 59 % on long inputs.
  This makes our result directly comparable to published practice instead of to an instrument we
  invented.

WHY IT MATTERS TO THIS PAPER SPECIFICALLY
  Our two task-benchmark nulls (PN-22 HellaSwag, PN-28 HumanEval+) are both at SHORT context. The
  literature reports 4-bit damage appearing at 128K. If RULER shows degradation at 131,072 where
  HumanEval+ showed none at 32,768, the two results are the same curve sampled at different
  depths, and the paper gains its long-context dimension rather than a stated limitation.

FIDELITY AND ITS ONE DEPARTURE
  Data is generated by RULER's OWN reference generators (scripts/data/synthetic/{niah,
  variable_tracking}.py) with the official templates and answer prefixes from its constants.py,
  and scored with its own `string_match_all` metric, reproduced here verbatim.
  DEPARTURE, stated: RULER's `OpenAIClient` is hardcoded to OpenAI/Azure endpoints (requires
  OPENAI_API_KEY, tiktoken cl100k_base, a fixed model->length table) and its requirements pull
  nemo-toolkit[all] + vllm==0.5.4 + transformers==4.44.2. We therefore serve the generated data
  through this project's own harness. Generation and scoring are RULER's; only transport is ours.

RESOURCE MATH, done before the harness (the discipline whose absence caused PN-30/PN-31)
  Each sample needs a FULL prefill of its own haystack and prefix caching cannot help, because
  every sample's haystack differs. At the measured ~600 tok/s prefill:
      8,192 -> 0.23 min/sample     32,768 -> 0.91      131,072 -> 3.64
  A flat n=25 would cost 8.0 h with ~75 % of it in the deepest rung alone, so sample counts are
  per-length: 25 / 25 / 12 -> 22.8 + 91.0 + 174.8 min = 4.8 h of prefill, ~5.8 h with model loads.
  RAM is not a factor (no logits buffering); VRAM is an ordinary serving load, far below the
  ceilings mapped in Wave 1.
"""
import argparse, json, os, subprocess, sys, time

sys.path.insert(0, "/srv/bench/e12/experiments")
sys.path.insert(0, "/srv/bench/RULER/scripts/data/synthetic")
import lib_e12 as L

E12, OUTD = "/srv/bench/e12", "/srv/bench/e12/ruler"
DATA, GEN = f"{OUTD}/data", "/srv/bench/RULER/scripts/data/synthetic"
PY = "/srv/bench/.venv-evalplus/bin/python"
TOKENIZER = "/srv/engines/nvfp4"

# Two arms: the ladder's extremes. Same reasoning as SSA S6 (R6, Miller/Anthropic) — with a fixed
# budget, two arms at the extremes resolve more than four arms spread thin.
ARMS = {"Q6_K_XL": "/srv/models/Qwen3.8-27B-UD-Q6_K_XL.gguf",     # reference / baseline
        "Q4_K_XL": "/srv/models/Qwen3.8-27B-UD-Q4_K_XL.gguf"}
REFERENCE = "Q6_K_XL"
TS = "56,44"                       # one ratio for both arms — controlled
LENGTHS = [8192, 32768, 131072]    # cheapest first; each length is a usable slice on its own
# Per-length sample counts. The deepest rung costs 16x the shallowest per sample (each sample
# needs its own full prefill and prefix caching cannot help), so a flat n would put ~75 % of the
# budget into one length. n=12 at 131,072 still resolves the size of effect the literature reports
# there (Red Hat: 85-88 % recovery for INT W4A16 at 128K, i.e. 12-15 point drops).
N_SAMPLES = {8192: 25, 32768: 25, 131072: 12}
N_SMOKE = 3
TASKS = ["niah", "variable_tracking"]


def log(*a):
    print(f"[{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}]", *a, flush=True)


def string_match_all(preds, refs):
    """RULER's own metric, reproduced verbatim from scripts/eval/synthetic/constants.py."""
    return round(sum([sum([1.0 if r.lower() in pred.lower() else 0.0 for r in ref]) / len(ref)
                      for pred, ref in zip(preds, refs)]) / len(preds) * 100, 2)


def ruler_template(task, key):
    import constants
    return constants.TASKS[task][key]


def generate(task, length, n=None, seed=42):
    """Invoke RULER's reference generator with its official template."""
    n = n or N_SAMPLES.get(length, 25)
    name = f"{task}_{length}"
    out = f"{DATA}/{name}/validation.jsonl"
    if os.path.exists(out):
        log(f"  {name}: already generated"); return out
    script = {"niah": "niah.py", "variable_tracking": "variable_tracking.py"}[task]
    cmd = [PY, script, "--save_dir", DATA, "--save_name", name,
           "--tokenizer_path", TOKENIZER, "--tokenizer_type", "hf",
           "--max_seq_length", str(length),
           "--tokens_to_generate", str(ruler_template(task, "tokens_to_generate")),
           "--num_samples", str(n), "--random_seed", str(seed),
           "--template", ruler_template(task, "template"),
           "--type_haystack", "noise"]
    if task == "niah":
        cmd += ["--type_needle_k", "words", "--type_needle_v", "numbers"]
    r = subprocess.run(cmd, cwd=GEN, capture_output=True, text=True, timeout=3600)
    if not os.path.exists(out):
        log(f"  {name}: GENERATION FAILED\n{(r.stderr or '')[-600:]}"); return None
    log(f"  {name}: generated {n} samples")
    return out


def run_arm(arm, length, rows, task):
    """Serve one task's samples to one arm at one length. Greedy, no-spec."""
    ntok = ruler_template(task, "tokens_to_generate")
    cmd, rc, err = L.launch(ARMS[arm], length, kv="q4_0", spec="none", sm="layer",
                            ts=TS, ctxcp=32, extra="")
    if rc != 0 or not L.wait_health(900)[0]:
        L.save_and_kill(f"s12-{arm}-{task}-c{length}-loadfail")
        return {"arm": arm, "task": task, "length": length, "ok": False,
                "detail": f"load failed rc={rc} {err[:200]}", "launch_cmd": cmd}
    if L.props_nctx() != length:
        L.save_and_kill(f"s12-{arm}-{task}-c{length}-nctx")
        return {"arm": arm, "task": task, "length": length, "ok": False,
                "detail": f"n_ctx mismatch {L.props_nctx()}"}
    preds, refs, meta = [], [], []
    t0 = time.time()
    for i, row in enumerate(rows):
        # RULER's own prompt construction: input + answer_prefix (call_api.py:305)
        prompt = row["input"] + row.get("answer_prefix", "")
        try:
            r = L.post("/completion", {"prompt": prompt, "n_predict": ntok,
                                       "cache_prompt": False, "temperature": 0,
                                       "top_p": 1, "top_k": 1, "seed": L.SEED}, timeout=7200)
            tm = r.get("timings", {}) or {}
            preds.append(r.get("content", "") or "")
            meta.append({"prompt_n": tm.get("prompt_n"), "predicted_n": tm.get("predicted_n")})
        except Exception as e:
            preds.append(""); meta.append({"error": str(e)[:200]})
        refs.append(row["outputs"])
        if (i + 1) % 10 == 0:
            log(f"    {arm} {task} c{length}: {i+1}/{len(rows)} ({time.time()-t0:.0f}s)")
    L.save_and_kill(f"s12-{arm}-{task}-c{length}")
    score = string_match_all(preds, refs)
    pn = [m.get("prompt_n") for m in meta if m.get("prompt_n")]
    rec = {"arm": arm, "task": task, "length": length, "ok": True, "score": score,
           "n": len(rows), "launch_cmd": cmd,
           "prompt_n_median": sorted(pn)[len(pn)//2] if pn else None,
           "prompt_n_min": min(pn) if pn else None, "prompt_n_max": max(pn) if pn else None,
           "n_empty": sum(1 for p in preds if not p.strip()),
           "seconds": round(time.time() - t0, 1),
           "preds": preds, "refs": refs}
    log(f"  {arm} {task} c{length}: score {score} (n={len(rows)}, {rec['n_empty']} empty, "
        f"{rec['seconds']}s, prompt_n median {rec['prompt_n_median']})")
    return rec


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", required=True, choices=["gen", "smoke"] +
                    [f"c{l}" for l in LENGTHS] + ["summarize"])
    a = ap.parse_args()
    os.makedirs(OUTD, exist_ok=True)
    path = f"{OUTD}/s12-ruler.json"
    out = (json.load(open(path)) if os.path.exists(path) else {
        "experiment": "s12-ruler", "source": "e12-s12", "run_ids": ["s12"],
        "benchmark": "RULER (arXiv 2404.06654), reference generators + official templates + string_match_all",
        "precedent": ["Red Hat RULER quantization study (accuracy recovery per length)",
                      "arXiv 2505.20276 quantization x long-context"],
        "departure": ("RULER's OpenAIClient targets OpenAI/Azure endpoints and its requirements "
                      "pin nemo-toolkit/vllm/transformers; data generation and scoring are RULER's, "
                      "transport is this project's harness"),
        "arms": list(ARMS), "reference": REFERENCE, "ts": TS, "kv": "q4_0",
        "spec": "NONE — PN-23/PN-26: speculation alters ~20 % of completions independently of quant",
        "sampling": "greedy (temperature 0, top_k 1)", "lengths": LENGTHS,
        "n_samples_per_length": N_SAMPLES, "tasks": TASKS,
        "metric": "RULER string_match_all; headline = accuracy recovery vs the reference arm per length",
        "started_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "cells": []})

    if a.phase == "gen":
        ok = True
        for L_ in LENGTHS:
            for t in TASKS:
                ok &= generate(t, L_) is not None
        sys.exit(0 if ok else 2)

    if a.phase == "smoke":
        # end-to-end on 3 samples at 4K: does the server answer RULER prompts at all?
        f = generate("niah", 4096, n=3)
        if not f:
            log("SMOKE FAIL: generation"); sys.exit(2)
        rows = [json.loads(x) for x in open(f)][:3]
        L.preflight()
        rec = run_arm(REFERENCE, 4096, rows, "niah")
        rec.pop("preds", None); rec.pop("refs", None)
        out["smoke"] = rec
        json.dump(out, open(path, "w"), indent=1)
        good = rec.get("ok") and rec.get("score", 0) > 0
        log(f"SMOKE: {'PASS' if good else 'FAIL'} — score {rec.get('score')}")
        sys.exit(0 if good else 2)

    if a.phase.startswith("c"):
        length = int(a.phase[1:])
        L.preflight()
        for task in TASKS:
            f = generate(task, length)
            if not f:
                continue
            rows = [json.loads(x) for x in open(f)][:N_SAMPLES.get(length, 25)]
            for arm in [REFERENCE] + [x for x in ARMS if x != REFERENCE]:
                rec = run_arm(arm, length, rows, task)
                side = f"{OUTD}/s12-preds-{arm}-{task}-c{length}.json"
                json.dump({"preds": rec.pop("preds", []), "refs": rec.pop("refs", [])},
                          open(side, "w"), indent=1)
                out["cells"].append(rec)
                json.dump(out, open(path, "w"), indent=1)
        n = sum(1 for c in out["cells"] if c.get("length") == length and c.get("ok"))
        log(f"length {length}: {n} cells ok")
        sys.exit(0 if n else 2)

    if a.phase == "summarize":
        rec = {}
        for c in out["cells"]:
            if c.get("ok"):
                rec.setdefault(str(c["length"]), {}).setdefault(c["task"], {})[c["arm"]] = c["score"]
        summ = {}
        for ln, tasks in rec.items():
            for task, arms in tasks.items():
                base = arms.get(REFERENCE)
                for arm, sc in arms.items():
                    if arm == REFERENCE or not base:
                        continue
                    summ.setdefault(ln, {})[f"{task}:{arm}"] = {
                        "score": sc, "baseline": base,
                        "accuracy_recovery_pct": round(100 * sc / base, 2) if base else None}
        out["accuracy_recovery"] = summ
        out["finished_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        json.dump(out, open(path, "w"), indent=1)
        log("ACCURACY RECOVERY vs " + REFERENCE + ": " + json.dumps(summ))
        sys.exit(0 if summ else 2)


if __name__ == "__main__":
    main()
